### ISSUE TITLE
Crash because trackt.tv account isn't set in preferences.

### ISSUE THREAD

**Issue by Powback** [ad-on-is/chilly#1]
Causes the movie and series list to return null, crashing the app before you're even able to access preferences.

**Comment by ad-on-is** [comment]
Does this happen on the emulator or on an actual Android TV device? Also, what Android TV version?

**Comment by Powback** [comment]
Emulator, I'm using an Nvidia Shield TV

On 25 Jul 2017, at 13:04, Adis Durakovic <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this happen on the emulator or on an actual Android TV device? Also, what Android TV version?

**Comment by ad-on-is** [comment]
ok, I'll look into that. thx

**Comment by Powback** [comment]
Just add a login check when pulling from trackt and loading preferences. Also the 123movieshd url has moved

On 25 Jul 2017, at 13:04, Adis Durakovic <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this happen on the emulator or on an actual Android TV device? Also, what Android TV version?

**Comment by ad-on-is** [comment]
fixed this and some other errors
